config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :combis do
    resources :bookings, only: [ :new, :create, :index ]
  end
  resources :bookings, only: [:update]
  get '/bookings/:id/refused', to: 'bookings#refused'
  get '/bookings/:id/validate', to: 'bookings#validate'
  get '/bookings/:id/review', to: 'bookings#review'
  get '/dashboard', to: 'accounts#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :combi
  belongs_to :user

  enum status: { "Wait for confirmation" => 0, "Accepted" => 1, "Refused" => 2, "Finish" => 3 }
end

app/models/combi.rb
class Combi < ApplicationRecord
  has_many :bookings
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :combis
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_after_action :verify_authorized
  def dashboard
    @bookings = current_user.bookings
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!, except: [:index, :show]
  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  require 'date'

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @combi = Combi.find(params[:combi_id])
    @booking.combi = @combi
    start = Date.parse(@booking.begin_date)
    last = Date.parse(@booking.end_date)
    @booking.price = ((last - start).to_i * @combi.price )
    @booking.user = current_user
    authorize @booking
    # fail
    if @booking.save
      redirect_to dashboard_path
    else
      redirect_to combi_path(@combi)
    end
  end

  def review
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.review_title = params[:booking][:review_title]
    @booking.review_content = params[:booking][:review_content]
    @booking.review_rating = params[:booking][:review_rating]
    authorize @booking
    if @booking.save
      redirect_to dashboard_path
    else
      render :review
    end
  end

  def validate
    @booking = Booking.find(params[:id])
    @booking.status = 1
    authorize @booking
    if @booking.save
      respond_to do |format|
        format.html { redirect_to dashboard_path }
        format.js
      end
    else
      respond_to do |format|
        alert = 'Something went wrong, please retry'
      end
    end
  end

  def refused
    @booking = Booking.find(params[:id])
    @booking.status = 2
    authorize @booking
    if @booking.save
      respond_to do |format|
        format.html { redirect_to dashboard_path }
        format.js
      end
    else
      respond_to do |format|
        alert = 'Something went wrong, please retry'
      end
    end
  end

  def destroy
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.permit(:begin_date, :end_date, :review_title, :review_content, :review_rating)
  end

end

app/controllers/combis_controller.rb
class CombisController < ApplicationController
  before_action :find_combi, only: [:edit, :update, :show]
  def index
    @combis = policy_scope(Combi)
    @combis = Combi.near(params[:search], 20) if params[:search] != ""
    # @combis = Combi

    @markers = @combis.map do |combi|
      {
        lat: combi.latitude,
        lng: combi.longitude,
        icon: "https://static.getjar.com/icon-50x50/78/829805_thm.png"
        # infoWindow: { content: render_to_string(partial: "/combis/map_box", locals: { combi: combi }) }
      }
    end
  end

  def show
    authorize @combi
    @booking = Booking.new
  end

  def new
    @combi = Combi.new
    authorize @combi
  end

  def create
    @combi = Combi.new(params_combi)
    @combi.user = current_user
    authorize @combi
    if @combi.save
      redirect_to combi_path(@combi)
    else
      # fail
      render :new
    end
  end

  def edit
    authorize @combi
  end

  def update
    authorize @combi
    if @combi.update(params_combi)
      redirect_to combi_path(@combi)
    else
      render :edit
    end
  end

  private

  def find_combi
    @combi = Combi.find(params[:id])
  end

  def params_combi
    params.require(:combi).permit(:model, :description, :price, :lat, :lgn, :address, :city, :photo, :photo_cache)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/dashboard.html.erb
<div class="wrapper">
  <div class="container">
    <div class="profil-container">
      <div class="profil_avatar_photo">
        <%= cl_image_tag(current_user.photo,
        width: 150, height: 150, crop: :thumb, gravity: :face) %>
      </div>
      <div class="user-information">
        <h4 id="profil">
           Name :
          <%= current_user.first_name %>
          <%= current_user.last_name %>
        </h4>
        <h4 id="profil">
          Mail :
          <%= current_user.email %>
          </h4>
      </div>
      <div class="modify-profil">
        <%= link_to "Update your profil", edit_user_registration_path(@current_user), class: "btn btn-success"%>
      </div>
    </div>

    <div class="reservation-container">
      <div class="booking">
        <h3>Your bookings:</h3>
        <ul class="no_padding_inline">
          <% @bookings.each do |booking| %>
            <li class="display-in-line">
              <div class="combi-model">
                <%= booking.combi.model %>
              </div>
              <div class="dashboard-combi-price">
                <p><%= booking.price %> €</p>
              </div>
              <div class="state_of_reservation">
                <%= booking.status %>
              </div>
              <div class="date">
                <p>Start at:</p>
                <p><%= booking.begin_date %></p>
                <p>Finish at:</p>
                <p><%= booking.end_date %></p>
              </div>
              <div class="review-div">
                <% if booking.status == "Accepted" %>
                  <%= link_to "Review the combi", "bookings/#{booking.id}/review", class: "btn btn-success"%>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="booking">
        <h3>Your combi's booking:</h3>
        <ul class="no_padding_inline">
          <% current_user.combis.each do |combi| %>
            <% combi.bookings.each do |booking| %>
              <li class="display-in-line" data-booking-id="<%= booking.id %>">
                <div class="combi-model">
                  <%= booking.combi.model %>
                </div>
                <div class="dashboard-combi-price">
                  <%= booking.price %>
                </div>
                <div class="state_of_reservation">
                  <%= booking.status %>
                </div>
                <div class="date">
                  <p>Start at:</p>
                  <p><%= booking.begin_date %></p>
                  <p>Finish at:</p>
                  <p><%= booking.end_date %></p>
                </div>
                <div class="button-action">
                  <% if booking.status == "Wait for confirmation" %>
                    <%= link_to "Accepted", "bookings/#{booking.id}/validate", class: "btn btn-success", remote: true %>
                    <%= link_to "Refuse", "bookings/#{booking.id}/refused", class: "btn btn-danger", remote: true %>
                  <% end %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="combi-container">
      <h3 class="haut-gauche">Combis:</h3>
      <%= link_to "Add a combi", new_combi_path(current_user), class: "btn btn-success haut-droit"%>
      <ul class="marge-top">
        <% current_user.combis.each do |combi| %>
          <li class="display-in-line">
            <div class="combi_image">
              <%= cl_image_tag combi.photo, height: 150, width: 200, crop: :fill %>
            </div>
            <div class="identify-combi">
              <%= combi.model %>
              <%= combi.description %>
              <%= combi.price %>
            </div>
            <div class="button_edit">
              <%= link_to "Edit your combi", edit_combi_path(combi), class: "btn btn-success"%>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/refused.js.erb
document.querySelector("[data-booking-id='<%= @booking.id %>']")
  .remove();

app/views/bookings/review.html.erb
<%= simple_form_for(@booking, method: :patch) do |f| %>
  <%= f.input :review_title %>
  <%= f.input :review_content %>
  <%= f.input :review_rating, collection: 0..5 %>
  <%= f.button :submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/bookings/validate.js.erb
var booking = document.querySelector("[data-booking-id='<%= @booking.id %>']")
console.log(booking)
booking.remove();

app/views/combis/_cards.html.erb
<div class="master-card">
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= combi.photo.present? ? cl_image_path(combi.photo, crop: :fill) : image_path('logo.jpg') %>);">
    <div class="card-description">
      <p><%= "#{combi.price} €" %></p>
    </div>
    <div class="card-category">
      <p><%= combi.model %></p>
    </div>
    <%= link_to "", combi_path(combi), class: "card-link"%>
  </div>
</div>

app/views/combis/_form.html.erb
<%= simple_form_for @combi do |f| %>
  <%= f.input :model, placeholder: 'Volswagen classic, california..' %>
  <%= f.input :description %>
  <%= f.input :address, input_html: { class: "search" } %>
  <%= f.input :price %>
  <%= f.input :photo, placeholder: 'Upload nice photo of your combi' %>
  <%= f.error_notification message: 'Something went wrong' %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/combis/edit.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(' <%= image_path("combiyellow.jpg") %>');">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <h2>Your combi</h2>
        <%= render 'form', combi: @combi %>
      </div>
    </div>
  </div>
</div>

app/views/combis/index.html.erb
<div class="white-wrapper">
  <div class="main-container">
    <div class="content">
      <div class= "cards-container">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-lg-12">
            <div class= "card-research">
              <%= render '/shared/searchform' %>
            </div>
          </div>
          <% @combis.each do |combi| %>
            <div class="col-xs-12 col-sm-6 col-lg-4">
              <%= render 'cards', combi: combi %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div
      id="map"
      data-markers="<%= @markers.to_json %>"
    ></div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/combis/new.html.erb
<div class="image-ground" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path("california.jpg") %>')">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h2 id="new-title">Add a combi</h2>
        <%= render 'form', combi: @combi %>
      </div>
    </div>
  </div>
</div>

app/views/combis/show.html.erb
<% if @combi && @combi.photo_url %>
  <div class="banner" style="background-image: url(<%= cl_image_path @combi.photo %>)">
  </div>
<% end %>
<div class="white-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8">
        <div class="combi_info">
          <h4>Model: <%= @combi.model %></h4>
          <p><%= @combi.description %></p>
          <p>address: <%= "#{@combi.address} #{@combi.city}" %></p>
          <h4>Price per day: <%= @combi.price %> €</h4>
        </div>
        <div class="combi_review">
          <h4>Reviews:</h4>
          <ul class="without_deco">
            <% @combi.bookings.each do |booking| %>
              <% if booking.review_content %>
                <li class="border_around">
                  <div class="display-in-line">
                    <div class="review_title">
                      <%= booking.review_title%>
                    </div>
                    <div class="review_rating">
                      <%= booking.review_rating %>
                    </div>
                  </div>
                  <div class="review_content">
                    <%= booking.review_content %>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul>

        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="reservation_card">
          <h4>Combi road trip</h4>
          <!-- A modifier avec la recherche-->
          <p>Address:</p>
          <p>
            <%= "#{@combi.address} #{@combi.city}" %>
          </p>
          <p>For:</p>
          <p><%= @combi.price %> €</p>
          <p>Date:</p>
          <%= form_tag [@combi, @booking], method: :post do %>
            <input type="date" name="begin_date">
            <input type="date" name="end_date">
            <hr>
            <%= submit_tag "Book it NOW!", class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>COMBI FREE</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="main">
    <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<div class="navbar-combi">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.jpg", class:"navbar-combi-brand", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-combi-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <a href="" class="nacombi-item navbar-combi-link">Share a combi</a>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-combi-item navbar-combi-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/combis/_cards.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= combi.photo.present? ? cl_image_path(combi.photo, crop: :fill) : image_path('logo.jpg') %>);">
  <div class="card-category"><%= combi.model %></div>
  <div class="card-description">
    <h2><%= combi.price %></h2>
  </div>
  <%= cl_image_path ( combi.user.photo,
      width: 400, height: 300, crop: :fill),
      :class => "card-user" %>
  <%= link_to "", combi_path(combi), :class => "card-link"%>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 50%), url('https://farm1.nzstatic.com/_proxy/imageproxy_1y/serve/exploring-new-zealand-by-kombi.jpg?focalpointx=50&focalpointy=50&height=420&outputformat=jpg&quality=75&source=2478340&transformationsystem=focalpointcrop&width=960&securitytoken=D26F59FAD019966D0798CB052376AAF5');">
  <h1>Combifree</h1>
  <p>Rent a combi, go on trip !</p>
  <div class = "form">
  <%= render '/shared/searchform' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>We <i class="fa fa-heart"></i> combi free at Le Wagon </p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-combi navbar-fixed-top">

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo1.png", class:"navbar-combi-brand", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-combi-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Rent my combi", new_combi_path, class: "navbar-combi-item navbar-combi-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-combi-item navbar-combi-link"  %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-combi-item navbar-combi-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchform.html.erb
<%= form_tag(combis_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search], placeholder:' please enter city..', class: "search btn btn-ligth") %>
  <input type="date" name="begin_date" class="btn btn-ligth">
  <input type="date" name="end_date" class="btn btn-ligth">
  <%= submit_tag ("Drive a combi"), class: 'btn btn-primary' %>
<% end %>